name: dotnet package

on: [push]

jobs:
  unittest:
    runs-on: ubuntu-latest
    env:
      BUILD_CONFIG: 'Release'
    steps:
      - uses: actions/checkout@v4

      - name: Setup dotnet
        uses: actions/setup-dotnet@v4
        id: setup-dotnet
        with:
          dotnet-version: '8.0.x'
          
      - name: Run unit tests
        run: dotnet test Minio.UnitTests --configuration $BUILD_CONFIG --logger trx --results-directory "UnitTestResults"

      - name: Upload unit test results
        uses: actions/upload-artifact@v4
        with:
          name: unit-tests
          path: UnitTestResults
        # Use always() to always run this step to publish test results when there are test failures
        if: ${{ always() }}

  integrationtest:
    runs-on: ubuntu-latest
    env:
      BUILD_CONFIG: 'Release'
    steps:
      - uses: actions/checkout@v4

      - name: Setup dotnet
        uses: actions/setup-dotnet@v4
        id: setup-dotnet
        with:
          dotnet-version: '8.0.x'

      - name: Run integration tests
        run: dotnet test Minio.IntegrationTests --configuration $BUILD_CONFIG --logger trx --results-directory "IntegrationTestResults"

      - name: Upload integration test results
        uses: actions/upload-artifact@v4
        with:
          name: integration-tests
          path: IntegrationTestResults
        # Use always() to always run this step to publish test results when there are test failures
        if: ${{ always() }}

  publish:
    runs-on: ubuntu-latest
    if: github.ref_type == 'tag' && startsWith(github.ref, 'refs/tags/v')
    needs: [unittest,integrationtest]
    env:
      BUILD_CONFIG: 'Release'
      VERSION: '0.0.0'
    steps:
      - uses: actions/checkout@v4

      - name: Setup dotnet
        uses: actions/setup-dotnet@v4
        id: setup-dotnet
        with:
          dotnet-version: '8.0.x'

      - name: Set Version Variable
        if: ${{ github.ref_type == 'tag' }}
        env:
          TAG: ${{ github.ref_name }}
        run: echo "VERSION=${TAG#v}" >> $GITHUB_ENV

      - name: Create NuGet package
        run: dotnet pack --configuration $BUILD_CONFIG /p:PackageVersion=$VERSION

      - name: Publish NuGet package
        run: nuget push **/*.nupkg -Source https://api.nuget.org/v3/index.json -ApiKey ${{secrets.NUGET_API_KEY}}
